### ISSUE TITLE
addCustomXMLPart doesnt seem to work. 

### ISSUE THREAD

**Issue by CharlesKuncheria** [OfficeDev/Word-Add-in-Work-with-custom-XML-parts#1]
The result property of asyncResult (object passed to callback) seem to be undefined.

**Comment by Rick-Kirkham** [comment]
@CharlesKuncheria 
Sorry it took so long to respond. Are you still having this issue?

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
